name: pollar_app
description: App wiki sobre refrigeradores/câmaras com manuais, modelos, etc.
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.1
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - lib/assets/images/brands/
    - lib/assets/images/models/
    - lib/assets/pdfs/
